name: glider_explorer_hvfixed
channels:
  - conda-forge
dependencies:
  - holoviews # might be affected by https://github.com/holoviz/holoviews/issues/5501
  - panel
  - dask
  - xarray
  - glidertools
  - hvplot
  - cmocean
  - pathlib
  - pandas
  - datashader
  - panel
  - argopy
